import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="customTheme" lang="en">
      <body className="bg-base-200 p-4 sm:p-6 lg:p-8 xl:p-10">
        {children}
      </body>
    </html>
  );
}
